# Generated by Django 5.1.5 on 2025-02-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='UserSession',
        ),
    ]
